### PR TITLE
Fix/no schema tooltip

### LINKED ISSUE #235: refactor: centralize <enum> → <enum>_tooltip mapping into shared lookup
Currently, pathway_type_tooltip is redundantly and manually defined in multiple datasets, despite being a deterministic function of pathway_type. This introduces unnecessary repetition and potential for inconsistency.

We should create a centralized mapping from pathway_type to pathway_type_tooltip, and use it to populate tooltip values programmatically.

AC:
- [ ] Create a shared lookup (e.g. pathway_type_tooltip_lookup) near the pbtar_schema.
- [ ] Update dataset generation logic to reference this mapping.
- [ ] Remove hardcoded tooltips from individual datasets.
- [ ] Add a test to ensure all used pathway_type values have a corresponding tooltip.

Reference:
From @jdhoffa in [PR #227](https://github.com/RMI/pbtar/pull/227#discussion_r2256007135)

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Remove ability to define arbitrary tooltips in the input data files.
* Removes field from schema,
* implements lookup table for tooltips in Pathway type and sector badges.
* Retains searching in tooltip text.

Closes #235

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
@jdhoffa This is functional, but in order for it to be actually correct, we should use real strings for the tooltip values. anything with `TKTK` is a placeholder.

Would you like to do final strings in this PR, or later?

Screenshot_2025-08-11_15 08 04

**Comment by jdhoffa** [comment]
> @jdhoffa This is functional, but in order for it to be actually correct, we should use real strings for the tooltip values. anything with `TKTK` is a placeholder.
> Would you like to do final strings in this PR, or later?

I reckon we should do the final strings in this PR, and I would defer to @jacobvjk as to what those should be. 
@jacobvjk for reference, we are looking to fill in the `tooltips` for the following values: 
`PathwayType` = `{Normative, Projection, Policy, Exploration}
`Sector` = `{Power, Oil & Gas, Coal, Renewables, Industrial, Transport, Buildings, Agriculture, N/A}`

**Comment by AlexAxthelm** [comment]
@jacobvjk These are the strings that will be in the tooltip when hovering over the **sector** and **pathway type** badges.

**Comment by jacobvjk** [comment]
@AlexAxthelm where exactly would that be? on the scenario cards or the detailed view?

**Comment by jdhoffa** [comment]
Examples on the PR deployed ENV: https://green-pebble-01f5d5c1e-247.westus2.6.azurestaticapps.net/
Screenshot 2025-08-13 at 11 54 31
Screenshot 2025-08-13 at 11 54 43

**Comment by jacobvjk** [comment]
Let's go with the agreed upon values from the PBTAR data model excel file:
- PathwayType = {Normative, Exploratory, Direct Policy, Predictive}
- Sector={Land Use, Agriculture, Real Estate, Industry, Steel, Cement, Chemicals, Coal Mining, Oil (Upstream), Gas (Upstream), Power, Transport, Road transport, Automotive, Aviation, Rail, Shipping, Other}`

**Comment by jdhoffa** [comment]
> Let's go with the agreed upon values from the PBTAR data model excel file:
> 
> * PathwayType = {Normative, Exploratory, Direct Policy, Predictive}
> * Sector={Land Use, Agriculture, Real Estate, Industry, Steel, Cement, Chemicals, Coal Mining, Oil (Upstream), Gas (Upstream), Power, Transport, Road transport, Automotive, Aviation, Rail, Shipping, Other}`

Thanks @jacobvjk. Any chance you could also provide the tooltip values for these? Not urgent, we can also get to it next week/ sprint, but we just need to define what to fill in there.

**Comment by jacobvjk** [comment]
My understanding was the tool tip shows all possible values for pathway type or sector? If so the tooltip values are the full lists o values above. If not, what do we want to show here?

**Comment by AlexAxthelm** [comment]
@jacobvjk These are the tooltips that show up differently for each sector badge. So hovering over `Transport` might say something like "Commercial logistics, does not include HDV manufacturing", or other small notes that would be useful to have if someone isn't sure on a meaning.

**Comment by jacobvjk** [comment]
@AlexAxthelm okay noted, thanks. I can draft something shortly, but we will probably update that again

**Comment by jacobvjk** [comment]
@jdhoffa @AlexAxthelm I would start with the following list, potentially to be corrected for odd wording:

Land Use - Agriculture, Forestry, Fishery, other forms of land use
Agriculture - Agricultural activities
Real Estate - Residential & Commercial buildings, their construction and energy use
Industry - Focused on manufacturing activities, especially heavy industries and hard-to-abate industries
Steel - Steel making, both primary and secondary. Can include upstream and downstream activities.
Cement - Cement manufacturing
Chemicals - Production of primary chemicals and/or chemicals for end use, such as plastics, fertilizer, pharmaceuticals
Coal Mining - Extraction of coal
Oil (Upstream) - Extraction of oil
Gas (Upstream) - Extraction of natural gas
Power - Includes power generation based on any energy source. Can also include power storage, transmission, and distribution.
Transport - Logistics of passengers and cargo
Road transport - Logistics of passengers and cargo on the road, by different means, I.e. types of vehicles.
Automotive - Automotive manufacturing.
Aviation - Logistics of passengers and cargo by airplane.
Rail - Logistics of passengers and cargo by train.
Shipping - Logistics of passengers and cargo by ship.
Other - Other climate relevant sectors that are not covered by any of the available categories.

File: src/utils/tooltipUtils.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
+import { PathwayType, Sector } from "../types";
+
+export const pathwayTypeTooltips: Record<PathwayType, string> = {
+  Normative: "Normative test tooltip TKTK",
+  Projection: "Projection test tooltip TKTK",
+  Policy: "Direct Policy test tooltip TKTK",
+  Exploration: "Exploratory test tooltip TKTK",
```
Comment (AlexAxthelm) [inline src/utils/tooltipUtils.ts]: @jacobvjk Could I get some tooltip descriptions for the Pathway types too? Thanks.

File: src/utils/searchUtils.ts [hunk 2]
```diff
@@ -50,7 +51,7 @@ export const filterScenarios = (
         scenario.modelTempIncrease,
         ...scenario.regions,
         ...scenario.sectors.map((s) => s.name),
-        ...scenario.sectors.map((s) => s.tooltip || ""),
+        ...scenario.sectors.map((s) => getSectorTooltip(s.name) || ""),
```
Comment (AlexAxthelm) [inline src/utils/searchUtils.ts:54]: @jdhoffa @lloyd-rmi Currently the sector tooltip text is included in the search corpus, but not pathway type tooltip. 

it feels wewird to have one, but not the other. Given that these are static strings now, I don't think it makes sense to keep them searchable, but your call.

Comment (jdhoffa) [reply src/utils/searchUtils.ts:54]: I don't mind either way, but one consideration is that we currently are able to visually highlight any searched text, which cues the user to know _why_ something shows up. 

If we allow search-ability within a tooltip, it may be less obvious.

Comment (AlexAxthelm) [reply src/utils/searchUtils.ts:54]: Flagged as #256, suggest we sort it out there, either way

File: src/utils/tooltipUtils.ts [hunk 3]
```diff
@@ -0,0 +1,44 @@
+import { PathwayType, Sector } from "../types";
+
+export const pathwayTypeTooltips: Record<PathwayType, string> = {
+  "Direct Policy": "Direct Policy test tooltip TKTK",
+  "Exploratory": "Exploratory test tooltip TKTK",
+  "Normative": "Normative test tooltip TKTK",
+  "Predictive": "Projection test tooltip TKTK",
```
Comment (AlexAxthelm) [inline src/utils/tooltipUtils.ts]: @jacobvjk @jdhoffa Sorry, touched the file and un-attached the comment. These are the names that match schema.

Comment (jdhoffa) [reply src/utils/tooltipUtils.ts]: @jacobvjk has validated the following tooltips (on Teams):

```suggestion
  "Direct Policy": "Outcomes based on legislated policy targets or commitments.",
  "Exploratory": "Examines a range of plausible futures without fixed goals.",
  "Normative": "Starts from a desired end state and works backward to actions.",
  "Predictive": "Projects likely futures based on current trends and assumptions.",
```

**Review by jdhoffa — DISMISSED** [review]
This is OK to merge!

**Comment by jdhoffa** [comment]
Actually, it looks like the Pathway tips aren't rendering on the front-end. I will investigate.

**Review by jdhoffa — APPROVED** [review]
